# base image
FROM alpine:3.5
#Installing python and pip
RUN apk add --update py2-pip
#installing python modules needed by the app
COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt
#copy files required for app to run
COPY app.py /usr/src/app/
COPY templates/index.html /usr/src/app/templates/
#which port the container should expose
EXPOSE 5000
# tell cmd to actually run the application
CMD ["python", "/usr/src/app/app.py"]